# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: ruby_utils 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "ruby_utils"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jordan Sexton"]
  s.date = "2014-05-27"
  s.description = "A toolkit of utility classes and Ruby core extensions."
  s.email = "jordan@jordansexton.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/ruby_utils.rb",
    "lib/ruby_utils/abstract_class.rb",
    "lib/ruby_utils/all.rb",
    "lib/ruby_utils/core_ext.rb",
    "lib/ruby_utils/core_ext/array.rb",
    "lib/ruby_utils/core_ext/array/options.rb",
    "lib/ruby_utils/core_ext/hash.rb",
    "lib/ruby_utils/core_ext/hash/operations.rb",
    "lib/ruby_utils/core_ext/kernel.rb",
    "lib/ruby_utils/core_ext/kernel/require.rb",
    "lib/ruby_utils/core_ext/object.rb",
    "lib/ruby_utils/core_ext/object/is_ary.rb",
    "lib/ruby_utils/core_ext/object/itself.rb",
    "lib/ruby_utils/core_ext/object/with.rb",
    "lib/ruby_utils/core_ext/object/yielding.rb",
    "lib/ruby_utils/gem_version.rb",
    "lib/ruby_utils/indifferent_set.rb",
    "lib/ruby_utils/lazy_hash.rb",
    "lib/ruby_utils/lazy_indifferent_hash.rb",
    "lib/ruby_utils/scoped_lazy_hash.rb",
    "lib/ruby_utils/scoped_lazy_indifferent_hash.rb",
    "lib/ruby_utils/version.rb",
    "lib/ruby_utils/void.rb",
    "ruby_utils.gemspec",
    "spec/ruby_utils_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/jordansexton/ruby_utils"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "A toolkit of utility classes and Ruby core extensions."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.2"])
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.2"])
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

